nucleos_dompdf:
    defaults:
        chroot: '%kernel.project_dir%/public'
        logOutputFile: '' # Prevent creating `/tmp/log.htm` which causes problems in some server configurations
        isRemoteEnabled: true
