framework:
<<<<<<< HEAD
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
=======
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
>>>>>>> origin/medlhr
        providers:
